version: "3.8"
name: "Ebra dev"
services:
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: ebra-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ebra-calls
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/migration:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7-alpine
    container_name: ebra-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: ebra-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  api:
    build:
      context: .
      dockerfile: dockerFile.dev
    ports:
      - "3000:3000"
    container_name: ebra-api-dev
    restart: unless-stopped
    command: ["npm", "run", "dev"]
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=ebra-calls # ← FIXED: underscore instead of hyphen
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=ebra-kafka
      - KAFKA_GROUP_ID=call-workers
      - API_KEY=secret
      - BASE_URL=http://localhost:3000
      - MAX_CONCURRENT_CALLS=30

volumes:
  postgres_data:
